### ISSUE TITLE
BUG: Error in rule trim_galore_PE rna-seq pipeline

### ISSUE THREAD

**Issue by dzijlmans** [vanheeringen-lab/seq2science#456]
**Describe the bug**
Running the rna-seq pipeline throws an error. 

[2020-08-07T093329.002444.snakemake.log](https://github.com/vanheeringen-lab/seq2science/files/5039975/2020-08-07T093329.002444.snakemake.log)

**To Reproduce**
***config.yaml***
```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results_full  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ./fastq_raw  # where to look for or download the fastqs


# contact info for multiqc report and trackhub
email: d.zijlmans@science.ru.nl

# produce a UCSC trackhub?
create_trackhub: True

# how to handle replicates
technical_replicates: merge    # change to "keep" to not combine them

# which quantifier to use
quantifier: htseq

# or specify which quantifier to use with the option to specify own parameters
#quantifier:
#  salmon:
#    quantifier_index: '-k 31'
#    quantify: '--seqBias --gcBias --validateMappings --recoverOrphans'
#    decoy_aware_index: False  # salmon only. Requires ~65 GB RAM for GRCh38


##### aligner and filter options are not used for the gene counts matrix if the quantifier is Salmon

# which aligner to use
aligner: star

# filtering after alignment
remove_blacklist: True
min_mapping_quality: 255  # (only keep uniquely mapped reads from STAR alignments)
only_primary_align: True


##### differential gene expression analysis (optional) #####

# specify contrasts to perform analysis
diffexp:
  deseq2:
    DE_params:
      multiple_testing_procedure: BH  # options: BH/IHW
      alpha_value: 0.05
      shrinkage_estimator: apeglm
    contrasts:
      - 'conditions_all_control'

#differential exon usage
dexseq: True
```
***samples.tsv***
```
# for help with filling out the samples.tsv:
# https://vanheeringen-lab.github.io/seq2science/content/workflows/rna_seq.html#filling-out-the-samples-tsv
# also make sure that you use tab as a delimiter
sample	assembly	descriptive_name	conditions
external-DZ-RNA1-R1WT-1-18363	GRCm38.p6	WT_1	control
external-DZ-RNA2-R1WT-2-18362	GRCm38.p6	WT_2	control
external-DZ-RNA3-R1WT-3-18361	GRCm38.p6	WT_3	control
external-DZ-RNA4-R1WT-4-18360	GRCm38.p6	WT_4	control
external-DZ-RNA5-EED226-1-18359	GRCm38.p6	EED226_1	treatmentA
external-DZ-RNA6-EED226-2-18358	GRCm38.p6	EED226_2	treatmentA
external-DZ-RNA7-EED226-3-18357	GRCm38.p6	EED226_3	treatmentA
external-DZ-RNA8-EED226-4-18356	GRCm38.p6	EED226_4	treatmentA
external-DZ-RNA9-siEZH2-1-18355	GRCm38.p6	siEZH2_1	treatmentB
external-DZ-RNA10-siEZH2-2-18354	GRCm38.p6	siEZH2_2	treatmentB
external-DZ-RNA11-siEZH2-3-18353	GRCm38.p6	siEZH2_3	treatmentB
external-DZ-RNA12-siEZH2-4-18352	GRCm38.p6	siEZH2_4	treatmentB
external-DZ-RNA13-siSFRS2-1-18351	GRCm38.p6	siSFRS2_1	treatmentC
external-DZ-RNA14-siSFRS2-2-18350	GRCm38.p6	siSFRS2_2	treatmentC
external-DZ-RNA15-siSFRS2-3-18349	GRCm38.p6	siSFRS2_3	treatmentC
external-DZ-RNA16-siSFRS2-4-18348	GRCm38.p6	siSFRS2_4	treatmentC
```

**Expected behavior**

**Screenshots**
