### ISSUE TITLE
BUG: star_align error rna-seq pipeline

### ISSUE THREAD

**Issue by dzijlmans** [vanheeringen-lab/seq2science#457]
**Describe the bug**
When I ran the pipeline yesterday, the analysis was at 156 of 203 steps (77% done), then it ran checkpoint strandedness_report and updated the htseq_count an ddexseq_count jobs, after which it went back to step 157 of 287 (55% done). It then threw an error ("KeyError: star_align) and finished prematurely (though it does not send this email and it apears the pipeline finished normally.

```
Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/00ae4980
Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/2f020311
[Thu Aug  6 18:46:16 2020]
Finished job 178.
156 of 203 steps (77%) done

[Thu Aug  6 18:46:16 2020]
checkpoint strandedness_report:
    input: /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA14-siSFRS2-2-18350.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA12-siEZH2-4-18352.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA7-EED226-3-18357.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA3-R1WT-3-18361.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA1-R1WT-1-18363.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA6-EED226-2-18358.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA15-siSFRS2-3-18349.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA10-siEZH2-2-18354.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA4-R1WT-4-18360.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA9-siEZH2-1-18355.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA16-siSFRS2-4-18348.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA13-siSFRS2-1-18351.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA5-EED226-1-18359.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA2-R1WT-2-18362.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA8-EED226-4-18356.strandedness.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/GRCm38.p6-external-DZ-RNA11-siEZH2-3-18353.strandedness.txt
    output: /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/inferred_strandedness.tsv
    jobid: 224
Downstream jobs will be updated after completion.

Job counts:
        count   jobs
        1       strandedness_report
        1
Updating job 9 (htseq_count).
Updating job 10 (htseq_count).
Updating job 11 (htseq_count).
Updating job 12 (htseq_count).
Updating job 13 (htseq_count).
Updating job 14 (htseq_count).
Updating job 15 (htseq_count).
Updating job 16 (htseq_count).
Updating job 17 (htseq_count).
Updating job 18 (htseq_count).
Updating job 19 (htseq_count).
Updating job 20 (htseq_count).
Updating job 21 (htseq_count).
Updating job 22 (htseq_count).
Updating job 23 (htseq_count).
Updating job 24 (htseq_count).
Updating job 208 (dexseq_count).
Updating job 209 (dexseq_count).
Updating job 210 (dexseq_count).
Updating job 211 (dexseq_count).
Updating job 212 (dexseq_count).
Updating job 213 (dexseq_count).
Updating job 214 (dexseq_count).
Updating job 215 (dexseq_count).
Updating job 216 (dexseq_count).
Updating job 217 (dexseq_count).
Updating job 218 (dexseq_count).
Updating job 219 (dexseq_count).
Updating job 220 (dexseq_count).
Updating job 221 (dexseq_count).
Updating job 222 (dexseq_count).
Updating job 223 (dexseq_count).
Updating job 8 (trackhub).
[Thu Aug  6 18:46:58 2020]
Finished job 224.
157 of 287 steps (55%) done

[Thu Aug  6 18:46:59 2020]
rule htseq_count:
    input: /home/dzijlmans/RNA-seq/DZ024/results/final_bam/GRCm38.p6-external-DZ-RNA12-siEZH2-4-18352.samtools-coordinate.bam, /home/dzijlmans/RNA-seq/DZ024/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/inferred_strandedness.tsv
    output: /home/dzijlmans/RNA-seq/DZ024/results/gene_counts/GRCm38.p6-external-DZ-RNA12-siEZH2-4-18352.counts.tsv
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/counts_matrix/GRCm38.p6-external-DZ-RNA12-siEZH2-4-18352.counts.log
    jobid: 307
    wildcards: assembly=GRCm38.p6, sample=external-DZ-RNA12-siEZH2-4-18352


[Thu Aug  6 18:46:59 2020]
rule trim_galore_PE:
    input: /home/dzijlmans/RNA-seq/DZ024/fastq_raw/external-DZ-RNA12-siEZH2-4-18352_R1.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/fastq_raw/external-DZ-RNA12-siEZH2-4-18352_R2.fastq.gz
    output: /home/dzijlmans/RNA-seq/DZ024/results/fastq_trimmed/external-DZ-RNA12-siEZH2-4-18352_R1_trimmed.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/results/fastq_trimmed/external-DZ-RNA12-siEZH2-4-18352_R2_trimmed.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/results/qc/trimming/external-DZ-RNA12-siEZH2-4-18352_R1.fastq.gz_trimming_report.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/trimming/external-DZ-RNA12-siEZH2-4-18352_R2.fastq.gz_trimming_report.txt
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/trim_galore_PE/external-DZ-RNA12-siEZH2-4-18352.log
    jobid: 146
    benchmark: /home/dzijlmans/RNA-seq/DZ024/results/benchmark/trim_galore_PE/external-DZ-RNA12-siEZH2-4-18352.benchmark.txt
    wildcards: sample=external-DZ-RNA12-siEZH2-4-18352
    threads: 6


[Thu Aug  6 18:46:59 2020]
rule htseq_count:
    input: /home/dzijlmans/RNA-seq/DZ024/results/final_bam/GRCm38.p6-external-DZ-RNA9-siEZH2-1-18355.samtools-coordinate.bam, /home/dzijlmans/RNA-seq/DZ024/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/inferred_strandedness.tsv
    output: /home/dzijlmans/RNA-seq/DZ024/results/gene_counts/GRCm38.p6-external-DZ-RNA9-siEZH2-1-18355.counts.tsv
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/counts_matrix/GRCm38.p6-external-DZ-RNA9-siEZH2-1-18355.counts.log
    jobid: 304
    wildcards: assembly=GRCm38.p6, sample=external-DZ-RNA9-siEZH2-1-18355


[Thu Aug  6 18:46:59 2020]
rule trim_galore_PE:
    input: /home/dzijlmans/RNA-seq/DZ024/fastq_raw/external-DZ-RNA10-siEZH2-2-18354_R1.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/fastq_raw/external-DZ-RNA10-siEZH2-2-18354_R2.fastq.gz
    output: /home/dzijlmans/RNA-seq/DZ024/results/fastq_trimmed/external-DZ-RNA10-siEZH2-2-18354_R1_trimmed.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/results/fastq_trimmed/external-DZ-RNA10-siEZH2-2-18354_R2_trimmed.fastq.gz, /home/dzijlmans/RNA-seq/DZ024/results/qc/trimming/external-DZ-RNA10-siEZH2-2-18354_R1.fastq.gz_trimming_report.txt, /home/dzijlmans/RNA-seq/DZ024/results/qc/trimming/external-DZ-RNA10-siEZH2-2-18354_R2.fastq.gz_trimming_report.txt
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/trim_galore_PE/external-DZ-RNA10-siEZH2-2-18354.log
    jobid: 88
    benchmark: /home/dzijlmans/RNA-seq/DZ024/results/benchmark/trim_galore_PE/external-DZ-RNA10-siEZH2-2-18354.benchmark.txt
    wildcards: sample=external-DZ-RNA10-siEZH2-2-18354
    threads: 6

Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/2f020311
Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/a1e5d68e
Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/a1e5d68e
Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/2f020311
[Thu Aug  6 18:48:55 2020]
Finished job 109.
158 of 287 steps (55%) done

[Thu Aug  6 18:48:55 2020]
rule htseq_count:
    input: /home/dzijlmans/RNA-seq/DZ024/results/final_bam/GRCm38.p6-external-DZ-RNA10-siEZH2-2-18354.samtools-coordinate.bam, /home/dzijlmans/RNA-seq/DZ024/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/inferred_strandedness.tsv
    output: /home/dzijlmans/RNA-seq/DZ024/results/gene_counts/GRCm38.p6-external-DZ-RNA10-siEZH2-2-18354.counts.tsv
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/counts_matrix/GRCm38.p6-external-DZ-RNA10-siEZH2-2-18354.counts.log
    jobid: 305
    wildcards: assembly=GRCm38.p6, sample=external-DZ-RNA10-siEZH2-2-18354

Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/2f020311
[Thu Aug  6 18:49:57 2020]
Finished job 180.
159 of 287 steps (55%) done

[Thu Aug  6 18:49:57 2020]
rule htseq_count:
    input: /home/dzijlmans/RNA-seq/DZ024/results/final_bam/GRCm38.p6-external-DZ-RNA11-siEZH2-3-18353.samtools-coordinate.bam, /home/dzijlmans/RNA-seq/DZ024/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf, /home/dzijlmans/RNA-seq/DZ024/results/qc/strandedness/inferred_strandedness.tsv
    output: /home/dzijlmans/RNA-seq/DZ024/results/gene_counts/GRCm38.p6-external-DZ-RNA11-siEZH2-3-18353.counts.tsv
    log: /home/dzijlmans/RNA-seq/DZ024/results/log/counts_matrix/GRCm38.p6-external-DZ-RNA11-siEZH2-3-18353.counts.log
    jobid: 306
    wildcards: assembly=GRCm38.p6, sample=external-DZ-RNA11-siEZH2-3-18353

Activating conda environment: /home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/seq2science/.snakemake/2f020311
[Thu Aug  6 20:40:53 2020]
Finished job 88.
160 of 287 steps (56%) done
Traceback (most recent call last):
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/__init__.py", line 703, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/workflow.py", line 953, in execute
    success = scheduler.schedule()
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/scheduler.py", line 394, in schedule
    run = self.job_selector(needrun)
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/scheduler.py", line 541, in job_selector
    c = list(map(self.job_reward, jobs))  # job rewards
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/scheduler.py", line 634, in job_reward
    return (job.priority, temp_size, input_size)
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/jobs.py", line 1025, in priority
    return self.dag.priority(self)
  File "/home/dzijlmans/anaconda3/envs/seq2science2/lib/python3.7/site-packages/snakemake/dag.py", line 383, in priority
    return self._priority[job]
KeyError: star_align
[Thu Aug  6 20:41:41 2020]
Finished job 146.
161 of 287 steps (56%) done
[Thu Aug  6 23:27:50 2020]
Finished job 250.
162 of 287 steps (56%) done
[Fri Aug  7 00:07:50 2020]
Finished job 305.
163 of 287 steps (57%) done
[Fri Aug  7 00:11:52 2020]
Finished job 304.
164 of 287 steps (57%) done
[Fri Aug  7 00:13:52 2020]
Finished job 306.
165 of 287 steps (57%) done
[Fri Aug  7 00:17:27 2020]
Finished job 307.
166 of 287 steps (58%) done
```

**To Reproduce**
Please include your **config.yaml**

```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ./fastq_raw  # where to look for or download the fastqs


# contact info for multiqc report and trackhub
email: d.zijlmans@science.ru.nl

# produce a UCSC trackhub?
create_trackhub: True

# how to handle replicates
technical_replicates: merge    # change to "keep" to not combine them

# which quantifier to use
quantifier: htseq

# or specify which quantifier to use with the option to specify own parameters
#quantifier:
#  salmon:
#    quantifier_index: '-k 31'
#    quantify: '--seqBias --gcBias --validateMappings --recoverOrphans'
#    decoy_aware_index: False  # salmon only. Requires ~65 GB RAM for GRCh38


##### aligner and filter options are not used for the gene counts matrix if the quantifier is Salmon

# which aligner to use
aligner: star

# filtering after alignment
remove_blacklist: True
min_mapping_quality: 255  # (only keep uniquely mapped reads from STAR alignments)
only_primary_align: True

##### differential gene expression analysis (optional) #####

# specify contrasts to perform analysis
diffexp:
  deseq2:
    DE_params:
      multiple_testing_procedure: BH  # options: BH/IHW
      alpha_value: 0.05
      shrinkage_estimator: apeglm
    contrasts:
      - 'conditions_all_control'

#differential exon usage
dexseq: True
```

***samples.tsv***
```
sample	assembly	descriptive_name	conditions
external-DZ-RNA1-R1WT-1-18363	GRCm38.p6	WT_1	control
external-DZ-RNA2-R1WT-2-18362	GRCm38.p6	WT_2	control
external-DZ-RNA3-R1WT-3-18361	GRCm38.p6	WT_3	control
external-DZ-RNA4-R1WT-4-18360	GRCm38.p6	WT_4	control
external-DZ-RNA5-EED226-1-18359	GRCm38.p6	EED226_1	treatmentA
external-DZ-RNA6-EED226-2-18358	GRCm38.p6	EED226_2	treatmentA
external-DZ-RNA7-EED226-3-18357	GRCm38.p6	EED226_3	treatmentA
external-DZ-RNA8-EED226-4-18356	GRCm38.p6	EED226_4	treatmentA
external-DZ-RNA9-siEZH2-1-18355	GRCm38.p6	siEZH2_1	treatmentB
external-DZ-RNA10-siEZH2-2-18354	GRCm38.p6	siEZH2_2	treatmentB
external-DZ-RNA11-siEZH2-3-18353	GRCm38.p6	siEZH2_3	treatmentB
external-DZ-RNA12-siEZH2-4-18352	GRCm38.p6	siEZH2_4	treatmentB
external-DZ-RNA13-siSFRS2-1-18351	GRCm38.p6	siSFRS2_1	treatmentC
external-DZ-RNA14-siSFRS2-2-18350	GRCm38.p6	siSFRS2_2	treatmentC
external-DZ-RNA15-siSFRS2-3-18349	GRCm38.p6	siSFRS2_3	treatmentC
external-DZ-RNA16-siSFRS2-4-18348	GRCm38.p6	siSFRS2_4	treatmentC
```

**Expected behavior**

**Screenshots**
