### ISSUE TITLE
Q: How to set-up custom genome indexes (with the scRNA-seq pipeline)?

### ISSUE THREAD

**Issue by Rebecza** [vanheeringen-lab/seq2science#617]
**Question**
Trying to generate a genome with custom additions 1. unsure where to place the settings for this in the config.yaml and 2. custom additions are not getting incorporated, not sure where to look for troubleshooting? 
**Subquestion:** Is the custom addition also possible with multiple files? (e.g. If I seperate 2 .fa/.gtf files with spaces?)

**What have I tried**
- The pipeline overall seems to run really nice! :) The problem starts with adding the custom .fa/.gtf files.
- See below my .config.yaml, I tried placing the `custom_genome_extension:`, `custom_annotation_extension:`, `custom_assembly_suffix:`, also right below the `fastq_dir:`-setting, although then the program is in trouble to locate my fastq files. Therefore, I now put it right before the `ref:`-settings, where the index-settings are stored.
- The picture below does show that the settings are saved.
- My output genome files don't seem to incorporate the additions (ERCC and reporter genes). This might also still be a Kallisto | Bustools related issue (although the genome-additions are set-up in such a way, that in an isolated KB-workflow these files worked with building the index!).
- I tried with and without setting the `custom_assembly_suffix:`.
- The pipeline is able to run normally, I cannot trace back any of my added genes in my genome files (e.g. GRCh38_t2g.txt, listing all the genes included in the index)

My config.yaml:
```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ../data/CMdiff_mon-EB-EHT_d4-26_all # where to look for fastqs

# contact info for multiqc report and trackhub
email: r.snabel@science.ru.nl

# how to handle replicates
technical_replicates: merge

# scRNA options
# seq2science does currently not support scrna-seq platforms that generate more than two fastq files, such as 10xv1.
quantifier:
  kallistobus:
    ## Quantification example ##
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose'
    #count: '-x 10XV3 --h5ad --verbose'

    ## Velocity example ##
    custom_genome_extension: ./genome_addons/ERCC92_reporter.fa
    custom_annotation_extension: ./genome_addons/ERCC92_reporter_biotype.gtf
    custom_assembly_suffix: "_ERCC_reporter"

    ref: '--workflow lamanno'
    count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 10XV3 --verbose --h5ad --workflow lamanno'

barcodefile: "../1col_barcode_384.tab"
```
Output after running: 
![afbeelding](https://user-images.githubusercontent.com/56538023/102479759-99b85f80-405f-11eb-94b3-b3dab2c0db71.png)

**Comment by Maarten-vd-Sande** [comment]
They shouldn't be part of 

```
quantifier:
  kallistobus:
```

It should be "unindented", and then (hopefully) should also work

**Comment by Maarten-vd-Sande** [comment]
This part seems to also be missing from the scRNA docs

**Comment by Rebecza** [comment]
I'm not sure where you want me to put it, I tried: 
```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ../data/CMdiff_mon-EB-EHT_d4-26_all # where to look for fastqs

# contact info for multiqc report and trackhub
email: r.snabel@science.ru.nl

# how to handle replicates
technical_replicates: merge

# scRNA options
# seq2science does currently not support scrna-seq platforms that generate more than two fastq files, such as 10xv1.
custom_genome_extension: ./genome_addons/ERCC92_reporter.fa
custom_annotation_extension: ./genome_addons/ERCC92_reporter_biotype.gtf
custom_assembly_suffix: "_ERCC_reporter"

quantifier:
  kallistobus:
    ## Quantification example ##
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose'
    #count: '-x 10XV3 --h5ad --verbose'

    ## Velocity example ##
    ref: '--workflow lamanno'
    count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 10XV3 --verbose --h5ad --workflow lamanno'

barcodefile: "../1col_barcode_384.tab"

```
As well as, after the quantifier block.. 
```
quantifier:
  kallistobus:
    ## Quantification example ##
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose'
    #count: '-x 10XV3 --h5ad --verbose'

    ## Velocity example ##
    ref: '--workflow lamanno'
    count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 10XV3 --verbose --h5ad --workflow lamanno'

custom_genome_extension: ./genome_addons/ERCC92_reporter.fa
custom_annotation_extension: ./genome_addons/ERCC92_reporter_biotype.gtf
custom_assembly_suffix: "_ERCC_reporter"

barcodefile: "../1col_barcode_384.tab"
```
This is the output I am consistently getting: (somehow the fastq path gets altered by this...)

![afbeelding](https://user-images.githubusercontent.com/56538023/102483971-de46f980-4065-11eb-950e-a2ab57d55979.png)

I tried making a `aligner:` section, but that is differently set-up for scRNA-seq with the KB workflow..

**Comment by Rebecza** [comment]
I would then also add it to the general part on the custom additions to the genome, which is now stating: 
![afbeelding](https://user-images.githubusercontent.com/56538023/102484289-544b6080-4066-11eb-9423-699d2b3ccebe.png)
(Or I might be missing something in the docs about that?(: )

**Comment by Rebecza** [comment]
WAIT! I am now running with:

```
# scRNA options
# seq2science does currently not support scrna-seq platforms that generate more than two fastq files, such as 10xv1.
quantifier:
  kallistobus:
    ## Quantification example ##
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose'
    #count: '-x 10XV3 --h5ad --verbose'

    ## Velocity example ##
    ref: '--workflow lamanno'
    count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 10XV3 --verbose --h5ad --workflow lamanno'

  custom_genome_extension: ./genome_addons/ERCC92_reporter.fa
  custom_annotation_extension: ./genome_addons/ERCC92_reporter_biotype.gtf
  custom_assembly_suffix: "_ERCC_reporter"

barcodefile: "../1col_barcode_384.tab"
```
Without any errors so far. I will later check my genome build again.
