### ISSUE TITLE
BUG: Kb-python segmentation fault

### ISSUE THREAD

**Issue by tilschaef** [vanheeringen-lab/seq2science#735]
**Describe the bug**
Since updating kb-python to version 0.26+ in the newest release of s2s there seem to be multiple occurences of segmentation errors when building the kb index for velocity or quantification analyses. This does not seems to affect the kite workflow. As a result,  the scRNA workflow terminates after 2 min and leaves an empty index directory (Credits to @JGASmits for the info).

From the log file:
`ngs_tools.gtf.Segment.SegmentError: Invalid segment [68899:68899`

Potential solution:

Downgrading kb-python to 0.25.1 yields the expected results or switch to Ensembl annotation.  

**To Reproduce**
```
quantifier:
  kallistobus:
    ref: ''--workflow lamanno"
    count: '-x 1,8,16:1,0,8:0,0,0 --verbose --loom --workflow lamanno'
```

**Expected behavior**
The index should build properly.
