### ISSUE TITLE
FR: update pyproject.toml

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#834]
pip pyproject.toml and setuptools dont work nicely together [yet](https://stackoverflow.com/questions/71517365/pyproject-toml-wont-find-project-name-with-setuptools-python-m-build-format).

I tried to make it work, but `entry points` and `packages` aren't implemented/documented properly yet. Here's what I got so far. So at least I didn't waste my afternoon too much.

btw, use `validate-pyproject` to check the file.
```toml
[project]
name = "seq2science"
version = "0.7.2"
description = "seq2science: easy pre-processing of ngs data."
readme = "README.md"
requires-python = ">3.6"
license = {file = "LICENSE"}
authors = [
    {name="Maarten van der Sande", email="M.vanderSande@science.ru.nl"},
    {name="Siebren Frölich", email="siebrenf@science.ru.nl"}
]
keywords = [
    "bioinformatics",
    "RNA-seq",
    "ATAC-seq",
    "ChIP-seq",
    "scRNA-seq",
    "scATAC-seq",
    "snakemake",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics"]

packages = ["seq2science"]
package_data = "{'seq2science':['envs/*', 'imgs/*', 'rules/*', 'schemas/*', 'schemas/*/*', 'scripts/*', 'scripts/**/*', 'workflows/*/*']}"
include_package_data = true

[project.urls]
documentation = "https://vanheeringen-lab.github.io/seq2science"
repository = "https://github.com/vanheeringen-lab/seq2science"
changelog = "https://github.com/vanheeringen-lab/seq2science/blob/master/CHANGELOG.md"

[project.scripts]
seq2science = "bin/seq2science"
deseq2science = "bin/deseq2science"

[build-system]
requires = ["setuptools==59.4.0", "wheel", "toml"]
build-backend = "setuptools.build_meta"

# flake8 does not support pyproject.toml (yet?!)
# [flake8] ...
```
