### ISSUE TITLE
"velo_assay" variable missing from scrna-prepocess when running lamanno 

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/seq2science#875]
When i run scrnaseq with preprocessing enabled on a velo workflow:

```

quantifier:
  kallistobus:
    ## Velocity example ##
    ref: '--workflow lamanno'
    count: '-x 1,8,16:1,0,8:0,0,0 --verbose --workflow lamanno --loom'

sc_preprocess:
   export_sce_objects: False
   run_sctk_qc: True
   sctk_data_type: cell
   use_alt_expr: True
   alt_exp_name: "ERCC_spikein"
   alt_exp_reg: "ERCC-*"
   sctk_mito_set: human-ensembl
   sctk_detect_mito: True
   sctk_detect_cell: False
   sctk_cell_calling: Knee

custom_annotation_extension: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/scRNAseq_iPSC_iLSCs/genomes/spike_in/ERC_92_name_biotype_ext.gtf
custom_genome_extension: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/scRNAseq_iPSC_iLSCs/genomes/spike_in/ERCC92_v2.fa
custom_assembly_suffix: "ERCCreporter"
barcodefile: "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/scRNAseq/1col_barcode_384.tab"

```

It crashes due toe the "velo_assay" variable being empty:
(pre-processing log:)
```
replicates       <- "FALSE"
iscite           <- "FALSE"
isvelo           <- "TRUE"
iskite           <- "FALSE"
velo_assay       <- ""
use_alt_expr     <- "FALSE"
alt_exp_name     <- ""
alt_exp_reg      <- ""
export_formats   <- ""

Wed Jun  1 09:47:31 2022 .. Preparing cell matrix from kallistobus (velocity) output!
Error in if (velo_assay == "spliced") { : argument is of length zero
Execution halted

```

It crashes therefore in the read_kb_counts.R script where it tries to read the velo_assay variable using:

velo_assay <- snakemake@config$sc_preprocess$velo_assay

However instead of 'spliced' or 'unspliced' it returns a "" wich causes it to crash.

I tried to look into how to fix it (i was hoping for a small PR), but the snakemake paramters are a bit of black magic to me still so i dont know where to begin.
